export enum EComponentType {
	SIMPLE_BRICK = "SIMPLE_BRICK",
	INDESTRUCTIBLE_BRICK = "INDESTRUCTIBLE_BRICK",
	BUTTON = "BUTTON",
	START_BUTTON = "START_BUTTON",
	LOADING_BAR = "LOADING_BAR",
	MAP = "MAP",
	TITLE = "TITLE",
}
