export enum EComponentType {
	SIMPLE_BRICK = "SIMPLE_BRICK",
	INDESTRUCTIBLE_BRICK = "INDESTRUCTIBLE_BRICK",
	START_BUTTON = "START_BUTTON",
	LOADING_BAR = "LOADING_BAR",
	MAP = "MAP",
	TITLE = "TITLE",
	WATER = "WATER",
	LEAVES = "LEAVES",
	BASE = "BASE",
	PLAYER_TANK = "PLAYER_TANK",
	ENEMY_TANK = "ENEMY_TANK",
}
