export enum EEventName {
	ASSETS_LOADED = "ASSETS_LOADED",
	ASSETS_LOADING_PROGRESS = "ASSETS_LOADING_PROGRESS",
	ASSETS_LOADING_FAILURE = "ASSETS_LOADING_FAILURE",
	GAME_OVER = "GAME_OVER",
	TANK_FIRE = "TANK_FIRE",
	TANK_DESTROYED = "TANK_DESTROYED",
	BASE_DESTROYED = "BASE_DESTROYED",
}
